<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 20.04.19
 * Time: 18:54
 */
namespace app\base;

use yii\base\Component;
use yii\web\Controller;

class BaseController extends Controller
{
    /**
     * @param \yii\base\Action $action
     * @param mixed $result
     * @return mixed
     */
    public function afterAction($action, $result)
    {
        $page = \Yii::$app->request->url; // так понятнее.
        \Yii::$app->session->set('page_url',$page);

        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}